// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerina/log;

# `AnthropicModelProvider` is a client class that provides an interface for interacting with Anthropic's Claude
# models deployed in Microsoft Foundry (Azure AI Foundry).
#
# Claude models on Azure are served through the **Anthropic Messages API** rather than an Azure OpenAI surface:
# requests go to `POST {serviceUrl}/v1/messages`, authenticate with the deployment's API key in the `x-api-key`
# header, carry the Messages API version in the `anthropic-version` header, and take **no** `api-version` query
# parameter. The `model` field of the request is the **deployment name** chosen at deployment time, which may
# differ from the underlying model id.
public isolated client class AnthropicModelProvider {
    *ai:ModelProvider;
    # Raw HTTP client pointed at the resolved `/anthropic` base URL. The Messages API has no generated Ballerina
    # connector, so the request body is serialized here and posted directly.
    private final http:Client anthropicClient;
    private final string apiKey;
    # The `anthropic-version` header value sent on every request.
    private final string anthropicVersion;
    # The Azure deployment name, sent as the `model` field of the request.
    private final string deploymentId;
    private final int maxTokens;
    private final decimal? temperature;
    private final readonly & Thinking? thinking;
    private final Effort? effort;

    # Initializes the Azure-hosted Anthropic (Claude) model with the given connection and model configuration.
    #
    # + serviceUrl - The base URL of the Azure Anthropic endpoint
    #              (`https://<resource>.services.ai.azure.com/anthropic`). A bare resource origin is completed
    #              with `/anthropic`, and a `/v1` or `/v1/messages` suffix copied from the deployment's target
    #              URI is trimmed, so any of those shapes may be passed.
    # + apiKey - The API key of the Claude deployment, sent in the `x-api-key` header
    # + deploymentId - The deployment name chosen when the Claude model was deployed. This can differ from the
    #                model id and is sent as the `model` field of the request.
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model. The
    #             Messages API requires this value; thinking tokens count towards it.
    # + temperature - The temperature for controlling randomness in the model's output. Leave it as `()` (the
    #               default) for the newer Claude models (Claude Opus 4.7 and later, Claude Sonnet 5, Claude
    #               Fable 5), which **reject** the parameter.
    # + thinking - The thinking configuration. Leave it as `()` to let the deployed model apply its own default.
    # + effort - The effort level, sent as `output_config.effort`. Leave it as `()` to use the service default
    #          (`"high"`). Claude Sonnet 4.5 and Claude Haiku 4.5 reject the parameter, and the accepted levels
    #          differ per model.
    # + anthropicVersion - The `anthropic-version` header value. Defaults to `"2023-06-01"`, the version
    #                    documented for Claude models in Microsoft Foundry.
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "Service URL"} string serviceUrl,
            @display {label: "API Key"} string apiKey,
            @display {label: "Deployment ID"} string deploymentId,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = (),
            @display {label: "Thinking"} Thinking? thinking = (),
            @display {label: "Effort"} Effort? effort = (),
            @display {label: "Anthropic Version"} string anthropicVersion = DEFAULT_ANTHROPIC_VERSION,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        if maxTokens <= 0 {
            return error ai:Error(string `The 'maxTokens' argument must be a positive integer; found ${
                maxTokens}.`);
        }
        if anthropicVersion.trim().length() == 0 {
            return error ai:Error("The 'anthropicVersion' argument must not be blank; it is sent as the " +
                    "'anthropic-version' header, which the Messages API requires.");
        }
        check validateThinking(thinking, maxTokens, temperature);
        if thinking is Thinking && thinking.'type == "enabled" {
            // Warned once here rather than per call: the `generate` method has to force the `getResults` tool,
            // which the Messages API rejects alongside manual extended thinking.
            log:printWarn("Manual extended thinking ('type: \"enabled\"') is not supported with a forced tool " +
                    "choice, so it is omitted from 'generate' requests. Use \"adaptive\" thinking, supported " +
                    "on Claude Opus 4.6 / Sonnet 4.6 and later, to reason while producing a structured result.",
                    deploymentId = deploymentId);
        }

        http:Client|error anthropicClient = new (resolveAnthropicBase(serviceUrl),
                toRawHttpConfig(connectionConfig));
        if anthropicClient is error {
            return error ai:Error("Failed to initialize the Azure Anthropic model provider", anthropicClient);
        }

        self.anthropicClient = anthropicClient;
        self.apiKey = apiKey;
        self.anthropicVersion = anthropicVersion;
        self.deploymentId = deploymentId;
        self.maxTokens = maxTokens;
        self.temperature = temperature;
        self.thinking = thinking.cloneReadOnly();
        self.effort = effort;
    }

    # Sends a chat request to the Claude model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider(ANTHROPIC_PROVIDER_NAME);
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temperature = self.temperature;
        if temperature is decimal {
            span.addTemperature(temperature);
        }
        // Best-effort span input logging; multimodal content that cannot be stringified is simply not logged.
        json|ai:Error jsonMessages = convertMessageToJson(messages);
        if jsonMessages is json {
            span.addInputMessages(jsonMessages);
        }

        AnthropicRequestParts|ai:Error parts = convertToAnthropicMessages(messages);
        if parts is ai:Error {
            // The cause carries what actually went wrong (an unsupported document, a missing media type), so it
            // is repeated in the message: the top-level message is what a caller sees first.
            ai:Error err = error("Error while preparing the Anthropic Messages API request: " + parts.message(),
                    parts);
            span.close(err);
            return err;
        }

        AnthropicTool[]? anthropicTools = ();
        if tools.length() > 0 {
            anthropicTools = convertToAnthropicTools(tools);
            span.addTools(tools);
        }
        // `tool_choice` is left unset: its default (`auto`) both lets the model answer directly and keeps
        // parallel tool calls enabled, which is what the module's parallel tool calling support relies on.
        map<json> request = buildAnthropicRequest(self.deploymentId, self.maxTokens, temperature, self.thinking,
                self.effort, parts, anthropicTools, (), stop);

        AnthropicMessagesResponse|ai:Error response = postAnthropicMessages(self.anthropicClient, self.apiKey,
                self.anthropicVersion, request, parts.usesFileSource);
        if response is ai:Error {
            log:printError("Error response received from the Anthropic Messages API", response);
            span.close(response);
            return response;
        }
        addAnthropicResponseDetailsToSpan(span, response);

        ai:Error? stopError = checkAnthropicStopReason(response);
        if stopError is ai:Error {
            span.close(stopError);
            return stopError;
        }

        ai:ChatAssistantMessage|ai:Error message = convertAnthropicResponseToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        if message.content is string {
            // Only a text response gets an output type; a response that is purely tool calls carries no text
            // output and is left untagged.
            span.addOutputType(observe:TEXT);
        }
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.azure.AnthropicGenerator"
    } external;
}
