// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerina/log;
import ballerinax/azure.openai.chat as chat;
import ballerinax/azure.openai.responses as responses;

const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# `OpenAiModelProvider` is a client class that provides an interface for interacting with Azure-hosted OpenAI
# language models.
#
# The provider can target either the Azure OpenAI **Chat Completions API** (the default) or the **Responses API**,
# selected through the `apiType` parameter. The concrete wire route additionally depends on the shape of the
# `serviceUrl`: a URL ending with `/v1` targets the Azure OpenAI **v1 GA** surface through the generated
# `ballerinax/azure.openai.chat` / `ballerinax/azure.openai.responses` connectors, while any other URL targets the
# **legacy** route (`?api-version=...`) through a raw HTTP client. See the `ApiType` documentation for the full
# routing matrix.
public isolated distinct client class OpenAiModelProvider {
    *ai:ModelProvider;
    # Generated Chat Completions connector for the v1 GA surface (`POST {serviceUrl}/chat/completions`).
    # Created only when `apiType` is `CHAT_COMPLETION` and the `serviceUrl` targets the v1 GA surface; `()` otherwise.
    private final chat:Client? chatClient;
    # Raw HTTP client for the legacy Chat Completions route
    # (`POST {serviceUrl}/openai/deployments/{deploymentId}/chat/completions?api-version=...`). Created only when
    # `apiType` is `CHAT_COMPLETION` and the `serviceUrl` targets the legacy surface; `()` otherwise. A raw client
    # (rather than the connector) is used so the request body can be serialized here and the correct token-limit
    # field (`max_tokens` vs `max_completion_tokens`) selected per api-version.
    private final http:Client? legacyChatClient;
    # Generated Responses connector for the v1 GA surface (`POST {serviceUrl}/responses`).
    # Created only when `apiType` is `RESPONSES` and the `serviceUrl` targets the v1 GA surface; `()` otherwise.
    private final responses:Client? responsesClient;
    # Raw HTTP client for the legacy Responses route (`POST {serviceUrl}/openai/responses?api-version=...`).
    # Created only when `apiType` is `RESPONSES` and the `serviceUrl` targets the legacy surface; `()` otherwise.
    private final http:Client? legacyResponsesClient;
    # `true` when the `serviceUrl` targets the v1 GA surface (ends with `/v1`); `false` for the legacy surface.
    private final boolean useV1;
    private final string apiKey;
    private final string deploymentId;
    # Date-based `api-version` used on the legacy routes; `()` on the v1 GA surface.
    private final string? apiVersion;
    # `preview`/`v1` api-version forwarded on the v1 GA surface, if the caller opted into one; `()` otherwise.
    private final string? v1ApiVersion;
    private final decimal? temperature;
    private final int maxTokens;
    private final ReasoningEffort? reasoning;
    private final ApiType apiType;

    # Initializes the Azure OpenAI model with the given connection configuration and model configuration.
    #
    # + serviceUrl - The base URL of the Azure OpenAI API endpoint. A URL ending with `/v1`
    #              (e.g. `https://<resource>.openai.azure.com/openai/v1`) targets the v1 GA surface; any other URL
    #              (e.g. `https://<resource>.openai.azure.com`) targets the legacy route.
    # + apiKey - The Azure OpenAI API key
    # + deploymentId - The deployment identifier for the specific model deployment in Azure
    # + apiVersion - The Azure OpenAI `api-version`. **Required** for legacy (non-`/v1`) service URLs
    #              (e.g. `"2024-10-21"`); on such URLs an api-version `>= 2024-08-01-preview` sends the token limit
    #              as `max_completion_tokens` (required by GPT-5/o-series models, which reject `max_tokens`) and
    #              older versions send `max_tokens`. For v1 (`/v1`) service URLs the value is optional and normally
    #              omitted; pass `"preview"` or `"v1"` to opt into a specific v1 surface (any other value is
    #              ignored on v1 URLs).
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output. Higher values (e.g., 0.8)
    #               make output more random, while lower values (e.g., 0.2) make it more focused and deterministic.
    #               Set it to `()` for models that do not support this parameter (e.g. GPT-5/o-series reasoning
    #               models).
    # + reasoningEffort - Reasoning effort level for reasoning models.
    # + apiType - The Azure OpenAI API surface to use. Defaults to `CHAT_COMPLETION`. Set to `RESPONSES` to use the
    #           Responses API instead.
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "Service URL"} string serviceUrl,
            @display {label: "API Key"} string apiKey,
            @display {label: "Deployment ID"} string deploymentId,
            @display {label: "API Version"} string? apiVersion = (),
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = DEFAULT_TEMPERATURE,
            @display {label: "Reasoning Effort"} ReasoningEffort? reasoningEffort = (),
            @display {label: "API Type"} ApiType apiType = CHAT_COMPLETION,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {

        self.apiKey = apiKey;
        self.deploymentId = deploymentId;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.reasoning = reasoningEffort;
        self.apiType = apiType;

        // Drop a single trailing slash so the suffix checks below operate on a canonical form.
        string trimmedUrl = serviceUrl.endsWith("/") ? serviceUrl.substring(0, serviceUrl.length() - 1) : serviceUrl;
        boolean isV1 = trimmedUrl.endsWith("/v1");
        self.useV1 = isV1;

        // Resolve the api-version for the selected surface.
        string? resolvedApiVersion = ();
        string? resolvedV1ApiVersion = ();
        if isV1 {
            // v1 GA does not require an api-version. Honor an explicit "preview"/"v1"; ignore date-based values.
            if apiVersion is string {
                string trimmedVersion = apiVersion.trim();
                if trimmedVersion == "preview" || trimmedVersion == "v1" {
                    resolvedV1ApiVersion = trimmedVersion;
                } else if trimmedVersion.length() > 0 {
                    log:printWarn("The 'apiVersion' argument is ignored for v1 ('/v1') Azure OpenAI service URLs; " +
                            "date-based api-versions apply only to legacy service URLs. Pass \"preview\" or \"v1\" " +
                            "to opt into a specific v1 surface.", apiVersion = apiVersion);
                }
            }
        } else {
            // The legacy route requires a date-based api-version query parameter.
            if apiVersion is () || apiVersion.trim().length() == 0 {
                return error ai:Error("The 'apiVersion' argument is required for legacy (non-'/v1') Azure OpenAI " +
                        "service URLs. Provide a date-based api-version (e.g. \"2024-10-21\") or use a " +
                        "'.../openai/v1' service URL.");
            }
            resolvedApiVersion = apiVersion;
        }
        self.apiVersion = resolvedApiVersion;
        self.v1ApiVersion = resolvedV1ApiVersion;

        // Base for the legacy raw-HTTP routes must end with `/openai` (the deployment/route segments are appended
        // per request).
        string legacyBase = trimmedUrl.endsWith("/openai") ? trimmedUrl : trimmedUrl + "/openai";

        // Create only the client required by the selected (apiType, surface) combination; unused fields stay `()`.
        if apiType == CHAT_COMPLETION {
            if isV1 {
                chat:Client|error chatClient = new (toChatConnectionConfig(apiKey, connectionConfig), trimmedUrl);
                if chatClient is error {
                    return error ai:Error("Failed to initialize Azure OpenAI Chat Completions (v1) client", chatClient);
                }
                self.chatClient = chatClient;
                self.legacyChatClient = ();
            } else {
                http:Client|error legacyChatClient = new (legacyBase, toRawHttpConfig(connectionConfig));
                if legacyChatClient is error {
                    return error ai:Error("Failed to initialize Azure OpenAI Chat Completions client", legacyChatClient);
                }
                self.legacyChatClient = legacyChatClient;
                self.chatClient = ();
            }
            self.responsesClient = ();
            self.legacyResponsesClient = ();
        } else {
            if isV1 {
                responses:Client|error responsesClient =
                        new (toResponsesConnectionConfig(apiKey, connectionConfig), trimmedUrl);
                if responsesClient is error {
                    return error ai:Error("Failed to initialize Azure OpenAI Responses (v1) client", responsesClient);
                }
                self.responsesClient = responsesClient;
                self.legacyResponsesClient = ();
            } else {
                http:Client|error legacyResponsesClient = new (legacyBase, toRawHttpConfig(connectionConfig));
                if legacyResponsesClient is error {
                    return error ai:Error("Failed to initialize Azure OpenAI Responses client", legacyResponsesClient);
                }
                self.legacyResponsesClient = legacyResponsesClient;
                self.responsesClient = ();
            }
            self.chatClient = ();
            self.legacyChatClient = ();
        }
    }

    # Sends a chat request to the OpenAI model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        if self.apiType == CHAT_COMPLETION {
            return self.chatViaChatCompletions(messages, tools, stop);
        }
        return self.chatViaResponses(messages, tools, stop);
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.azure.Generator"
    } external;

    // ===== Chat Completions API path =====

    private isolated function chatViaChatCompletions(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        span.addOutputType(observe:TEXT);
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        // Best-effort span input logging; multimodal content that cannot be stringified is simply not logged.
        json|ai:Error jsonMsg = convertMessageToJson(messages);
        if jsonMsg is json {
            span.addInputMessages(jsonMsg);
        }

        chat:OpenAIChatCompletionRequestMessage[]|ai:Error completionMessages
                = self.prepareCompletionRequestMessages(messages);
        if completionMessages is ai:Error {
            ai:Error err = error("Error while preparing completion request messages", completionMessages);
            span.close(err);
            return err;
        }

        chat:ChatCompletionsBody request = {
            model: self.deploymentId,
            messages: completionMessages
        };
        decimal? temperature = self.temperature;
        if temperature is decimal {
            request.temperature = temperature;
        }
        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort {
            request.reasoning_effort = reasoningEffort;
        }
        if stop is string {
            request.stop = stop;
        }
        if tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }
        applyMaxTokens(request, self.maxTokens, self.useV1 || usesMaxCompletionTokens(self.apiVersion ?: ""));

        ChatCompletionResult|error response = postChatCompletion(self.chatClient, self.legacyChatClient, self.useV1,
                self.apiKey, self.deploymentId, self.apiVersion, self.v1ApiVersion, request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Chat Completions API", err);
            span.close(err);
            return err;
        }

        chat:OpenAICreateChatCompletionResponseChoices[] choices = response.choices;
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        string? responseId = response.id;
        if responseId is string {
            span.addResponseId(responseId);
        }
        chat:OpenAICompletionUsage? usage = response.usage;
        if usage is chat:OpenAICompletionUsage {
            span.addInputTokenCount(usage.prompt_tokens);
            span.addOutputTokenCount(usage.completion_tokens);
        }
        span.addFinishReason(choices[0].finish_reason);

        chat:OpenAIChatCompletionResponseMessage message = choices[0].message;
        ai:ChatAssistantMessage|error chatAssistantMessage = self.convertChatCompletionsResponseToAssistantMessage(message);
        if chatAssistantMessage is error {
            span.close(chatAssistantMessage);
            return error ai:LlmInvalidResponseError("Error while parsing the model response", chatAssistantMessage);
        }
        if chatAssistantMessage.toolCalls is ai:FunctionCall[] {
            span.close();
            return chatAssistantMessage;
        }

        span.addOutputMessages(chatAssistantMessage);
        span.addOutputType(observe:TEXT);
        span.close();
        return chatAssistantMessage;
    }

    // ===== Responses API path =====

    private isolated function chatViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        [responses:OpenAIInputItem[], string?]|ai:Error responseInput = convertToResponsesInput(messages);
        if responseInput is ai:Error {
            ai:Error err = error("Error while transforming input for Responses API", responseInput);
            span.close(err);
            return err;
        }
        [responses:OpenAIInputItem[], string?] [inputItems, instructions] = responseInput;

        responses:OpenAICreateResponse request = {
            model: self.deploymentId,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: false
        };
        decimal? temperature = self.temperature;
        if temperature is decimal {
            request.temperature = temperature;
        }
        if instructions is string {
            request.instructions = instructions;
        }
        if stop is string {
            log:printWarn("The 'stop' parameter is not supported by the Responses API and will be ignored.",
                model = self.deploymentId);
        }
        if tools.length() > 0 {
            request.tools = convertToResponsesTools(tools);
            span.addTools(tools);
        }
        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort {
            request.reasoning = {effort: reasoningEffort};
        }

        responses:InlineResponse200|error response = postResponsesRequest(self.responsesClient,
                self.legacyResponsesClient, self.useV1, self.apiKey, self.apiVersion, self.v1ApiVersion, request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Responses API", err);
            span.close(err);
            return err;
        }

        ai:Error? statusError = checkResponseStatus(response);
        if statusError is ai:Error {
            span.close(statusError);
            return statusError;
        }

        span.addResponseId(response.id);
        responses:OpenAIResponseUsage? usage = response.usage;
        if usage is responses:OpenAIResponseUsage {
            span.addInputTokenCount(usage.input_tokens);
            span.addOutputTokenCount(usage.output_tokens);
        }
        span.addFinishReason(response.status ?: "completed");

        ai:ChatAssistantMessage|ai:Error message = convertResponsesOutputToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // ===== Chat Completions helper methods =====

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages)
            returns chat:OpenAIChatCompletionRequestMessage[]|ai:Error {
        chat:OpenAIChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push(check self.mapUserMessage(messages));
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage {
                chatCompletionRequestMessages.push(check self.mapUserMessage(message));
            } else if message is ai:ChatSystemMessage {
                AzureChatSystemMessage systemMessage = {
                    content: check getChatMessageStringContent(message.content),
                    name: message?.name
                };
                chatCompletionRequestMessages.push(systemMessage);
            } else if message is ai:ChatAssistantMessage {
                AzureChatAssistantMessage assistantMessage = {};
                ai:FunctionCall[]? toolCalls = message.toolCalls;
                if toolCalls is ai:FunctionCall[] && toolCalls.length() > 0 {
                    assistantMessage.tool_calls = from ai:FunctionCall tc in toolCalls
                        select {
                            id: tc.id ?: string `call_${tc.name}`,
                            'function: {
                                name: tc.name,
                                arguments: (tc.arguments ?: {}).toJsonString()
                            }
                        };
                }
                string? content = message?.content;
                if content is string {
                    assistantMessage.content = content;
                }
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatFunctionMessage {
                AzureChatToolMessage toolMessage = {
                    content: message?.content ?: "",
                    tool_call_id: message.id ?: string `call_${message.name}`
                };
                chatCompletionRequestMessages.push(toolMessage);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function mapUserMessage(ai:ChatUserMessage message)
            returns AzureChatUserMessage|ai:Error {
        string|ai:Prompt messageContent = message.content;
        if messageContent is string {
            return {content: messageContent, name: message?.name};
        }
        DocumentContentPart[] contentParts = check generateChatCreationContent(messageContent);
        return {content: contentParts, name: message?.name};
    }

    private isolated function convertChatCompletionsResponseToAssistantMessage(
            chat:OpenAIChatCompletionResponseMessage message) returns ai:ChatAssistantMessage|error {
        ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
        chatAssistantMessage.content = message.content;

        chat:OpenAIChatCompletionMessageToolCallsItem? toolCalls = message.tool_calls;
        if toolCalls is chat:OpenAIChatCompletionMessageToolCallsItem && toolCalls.length() > 0 {
            ai:FunctionCall[] functionCalls = [];
            foreach chat:OpenAIChatCompletionMessageToolCall|chat:OpenAIChatCompletionMessageCustomToolCall tc
                    in toolCalls {
                if tc is chat:OpenAIChatCompletionMessageCustomToolCall {
                    return error ai:LlmError("Custom tools are not supported, Found: " + tc.toJsonString());
                }
                chat:OpenAIChatCompletionMessageToolCall toolCall = <chat:OpenAIChatCompletionMessageToolCall>tc;
                json arguments = check toolCall.'function.arguments.fromJsonString();
                functionCalls.push({
                    id: toolCall.id,
                    name: toolCall.'function.name,
                    arguments: check arguments.cloneWithType()
                });
            }
            if functionCalls.length() > 0 {
                chatAssistantMessage.toolCalls = functionCalls;
            }
            return chatAssistantMessage;
        }

        // Fall back to the deprecated `function_call` field for backward compatibility.
        chat:OpenAIChatCompletionResponseMessageFunctionCall? functionCall = message.function_call;
        if functionCall is chat:OpenAIChatCompletionResponseMessageFunctionCall {
            json arguments = check functionCall.arguments.fromJsonString();
            chatAssistantMessage.toolCalls = [
                {
                    name: functionCall.name,
                    arguments: check arguments.cloneWithType()
                }
            ];
        }
        return chatAssistantMessage;
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        json[] result = [];
        foreach ai:ChatMessage msg in messages {
            if msg is ai:ChatUserMessage|ai:ChatSystemMessage {
                result.push(check convertMessageToJson(msg));
            } else {
                result.push(msg);
            }
        }
        return result;
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {
        return {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
    }
    return messages;
}

isolated function convertFunctionsToCompletionTools(ai:ChatCompletionFunctions[] functions)
        returns chat:OpenAIChatCompletionTool[] {
    return from ai:ChatCompletionFunctions fn in functions
        select {
            'type: "function",
            'function: {
                name: fn.name,
                description: fn.description,
                parameters: fn.parameters ?: {}
            }
        };
}
