// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerina/log;
import ballerinax/azure.openai.chat as chat;
import ballerinax/azure.openai.responses as responses;

const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# The Azure OpenAI API surface used by the `OpenAiModelProvider`.
public enum ApiType {
    # Use the Azure OpenAI **Responses API**. This is the default. The exact route is derived from the
    # `serviceUrl`: if the URL ends with `/v1` the v1 GA surface `POST {serviceUrl}/responses` is used
    # (no `api-version`); otherwise the legacy preview route
    # `POST {serviceUrl}/openai/responses?api-version={apiVersion}` is used.
    RESPONSES,
    # Use the Azure OpenAI **Chat Completions API**
    # (`POST {serviceUrl}/openai/deployments/{deploymentId}/chat/completions?api-version={apiVersion}`).
    CHAT_COMPLETION
}

# `OpenAiModelProvider` is a client class that provides an interface for interacting with Azure-hosted OpenAI
# language models.
#
# The provider can target either the Azure OpenAI **Responses API** or the **Chat Completions API**. The API
# surface is selected at initialization time through the `apiType` parameter and defaults to
# `RESPONSES`. The Chat Completions surface is backed by the generated `ballerinax/azure.openai.chat`
# connector. For the Responses surface the route depends on the `serviceUrl`: a URL ending with `/v1`
# targets the v1 GA surface through the generated `ballerinax/azure.openai.responses` connector, while any
# other URL targets the legacy preview route (`/openai/responses?api-version=...`) through a raw HTTP client.
public isolated client class OpenAiModelProvider {
    *ai:ModelProvider;
    # Raw HTTP client for the Chat Completions route. Created only when `apiType` is `CHAT_COMPLETION`; `()` otherwise.
    # A raw client (rather than the generated `chat:Client`) is used so the request body can be serialized in this
    # module and the correct token-limit field (`max_tokens` vs `max_completion_tokens`) selected per api-version.
    private final http:Client? llmClient;
    # Generated Responses connector used for the v1 GA surface (`POST {serviceUrl}/responses`).
    # Created only when `apiType` is `RESPONSES` and the `serviceUrl` targets the v1 GA surface; `()` otherwise.
    private final responses:Client? responsesClient;
    # Raw HTTP client used for the legacy preview route (`POST {serviceUrl}/openai/responses?api-version=...`).
    # Created only when `apiType` is `RESPONSES` and the `serviceUrl` targets the legacy preview surface; `()` otherwise.
    private final http:Client? legacyResponsesClient;
    # `true` when the Responses path targets the v1 GA surface; `false` for the legacy preview route.
    private final boolean useV1Responses;
    private final string apiKey;
    private final string deploymentId;
    private final string apiVersion;
    private final decimal? temperature;
    private final int maxTokens;
    private final responses:ReasoningEffort? reasoning;
    private final ApiType apiType;

    # Initializes the Azure OpenAI model with the given connection configuration and model configuration.
    #
    # + serviceUrl - The base URL of the Azure OpenAI API endpoint (e.g. `https://<resource>.openai.azure.com`)
    # + apiKey - The Azure OpenAI API key
    # + deploymentId - The deployment identifier for the specific model deployment in Azure
    # + apiVersion - The Azure OpenAI API version (e.g. `"2025-04-01-preview"`). Used by the Chat Completions API
    #              and by the legacy preview Responses route (`/openai/responses?api-version=...`). It is not sent
    #              on the Responses v1 GA surface (a `serviceUrl` ending with `/v1`), which does not accept it.
    #              On the Chat Completions surface, an api-version `>= 2024-08-01-preview` automatically sends the
    #              token limit as `max_completion_tokens` (required by GPT-5/o-series models, which reject
    #              `max_tokens`); older versions send `max_tokens` for backward compatibility.
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output.
    #               Higher values (e.g., 0.8) make output more random, while lower values (e.g., 0.2) make it more
    #               focused and deterministic. Some models may not support this parameter, in which case set it to `()`.
    # + reasoningEffort - Reasoning effort level for reasoning models.
    # + apiType - The Azure OpenAI API surface to use. Defaults to `RESPONSES`. Set to `CHAT_COMPLETION` to use the
    #           Chat Completions API instead.
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "Service URL"} string serviceUrl,
            @display {label: "API Key"} string apiKey,
            @display {label: "Deployment ID"} string deploymentId,
            @display {label: "API Version"} string apiVersion,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = DEFAULT_TEMPERATURE,
            @display {label: "Reasoning Effort"} responses:ReasoningEffort? reasoningEffort = (),
            @display {label: "API Type"} ApiType apiType = RESPONSES,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {

        self.deploymentId = deploymentId;
        self.apiKey = apiKey;
        self.apiVersion = apiVersion;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.reasoning = reasoningEffort;
        self.apiType = apiType;

        // Drop a single trailing slash so the suffix checks below operate on a canonical form.
        string trimmedUrl = serviceUrl.endsWith("/") ? serviceUrl.substring(0, serviceUrl.length() - 1) : serviceUrl;

        // A `serviceUrl` ending with `/v1` (e.g. `https://<resource>.openai.azure.com/openai/v1`) selects the
        // Azure OpenAI Responses **v1 GA** surface, which is served at `{serviceUrl}/responses` with no
        // `api-version`. Any other URL uses the legacy preview route `{...}/openai/responses?api-version=...`.
        boolean isV1 = trimmedUrl.endsWith("/v1");
        self.useV1Responses = isV1;

        // The Chat Completions API is always deployment-scoped under `/openai`. Strip a trailing `/v1` (the v1 GA
        // Responses form) before appending `/openai` so the Chat Completions route stays valid regardless of which
        // Responses surface the `serviceUrl` targets.
        string chatBase = isV1 ? trimmedUrl.substring(0, trimmedUrl.length() - "/v1".length()) : trimmedUrl;
        string normalizedUrl = chatBase.endsWith("/openai") ? chatBase : chatBase + "/openai";

        // Create only the client required by the selected `apiType`; the unused client fields stay `()`.
        if apiType == CHAT_COMPLETION {
            // Raw HTTP client bound to the `.../openai` base. The `api-key` header is added per request (see
            // `chatViaChatCompletions`/`generateLlmResponse`) rather than through connector auth, so the request
            // body can be built here and the token-limit field chosen per api-version. `laxDataBinding` mirrors
            // the generated connector so real Azure responses bind identically.
            http:ClientConfiguration chatHttpConfig = {
                httpVersion: connectionConfig.httpVersion,
                http1Settings: connectionConfig.http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation,
                laxDataBinding: true
            };
            http:Client|error llmClient = new (normalizedUrl, chatHttpConfig);
            if llmClient is error {
                return error ai:Error("Failed to initialize Chat Completions client", llmClient);
            }
            self.llmClient = llmClient;
            self.responsesClient = ();
            self.legacyResponsesClient = ();
        } else if isV1 {
            // v1 GA surface: the generated connector posts `/responses` onto the `.../openai/v1` base URL.
            responses:ConnectionConfig responsesConfig = {
                auth: {api\-key: apiKey},
                httpVersion: connectionConfig.httpVersion,
                http1Settings: connectionConfig.http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation
            };
            responses:Client|error responsesApiClient = new (responsesConfig, trimmedUrl);
            if responsesApiClient is error {
                return error ai:Error("Failed to initialize Responses API client", responsesApiClient);
            }
            self.responsesClient = responsesApiClient;
            self.legacyResponsesClient = ();
            self.llmClient = ();
        } else {
            // Legacy preview route: the generated connector cannot attach the required `api-version` query
            // parameter, so use a raw HTTP client bound to the `.../openai` base and add `api-version` per request.
            http:ClientConfiguration legacyHttpConfig = {
                httpVersion: connectionConfig.httpVersion,
                http1Settings: connectionConfig.http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation,
                // Match the generated `responses` connector, which enables lax data binding by default, so the
                // legacy route deserializes real Azure responses identically to the v1 GA surface.
                laxDataBinding: true
            };
            http:Client|error legacyClient = new (normalizedUrl, legacyHttpConfig);
            if legacyClient is error {
                return error ai:Error("Failed to initialize Responses API client", legacyClient);
            }
            self.legacyResponsesClient = legacyClient;
            self.responsesClient = ();
            self.llmClient = ();
        }
    }

    # Sends a chat request to the OpenAI model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        if self.apiType == CHAT_COMPLETION {
            return self.chatViaChatCompletions(messages, tools, stop);
        }
        return self.chatViaResponses(messages, tools, stop);
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.azure.Generator"
    } external;

    // ===== Chat Completions API path =====

    private isolated function chatViaChatCompletions(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        http:Client? llmClient = self.llmClient;
        if llmClient is () {
            return error ai:LlmConnectionError("Chat Completions client is not initialized");
        }
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        span.addOutputType(observe:TEXT);
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error jsonMsg = convertMessageToJson(messages);
        if jsonMsg is ai:Error {
            ai:Error err = error("Error while transforming input", jsonMsg);
            span.close(err);
            return err;
        }
        span.addInputMessages(jsonMsg);

        chat:chatCompletionRequestMessage[]|ai:Error completionMessages
                = self.prepareCompletionRequestMessages(messages);
        if completionMessages is ai:Error {
            ai:Error err = error("Error while preparing completion request messages", completionMessages);
            span.close(err);
            return err;
        }

        chat:createChatCompletionRequest request = {
            messages: completionMessages,
            temperature: self.temperature,
            max_tokens: self.maxTokens
        };
        responses:ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is "low"|"medium"|"high" {
            request.reasoning_effort = reasoningEffort;
        }
        if stop is string {
            request.stop = stop;
        }
        if tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }

        map<json>|ai:Error body = buildChatCompletionBody(request, self.apiVersion, self.reasoning);
        if body is ai:Error {
            span.close(body);
            return body;
        }

        chat:createChatCompletionResponse|error response = llmClient->post(
            string `/deployments/${self.deploymentId}/chat/completions?api-version=${self.apiVersion}`,
            body, {"api-key": self.apiKey});
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Chat Completions API", err);
            span.close(err);
            return err;
        }

        chat:createChatCompletionResponse_choices[] choices = response.choices;
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        chat:completionUsage? usage = response.usage;
        if usage is chat:completionUsage {
            span.addInputTokenCount(usage.prompt_tokens);
            span.addOutputTokenCount(usage.completion_tokens);
        }
        span.addFinishReason(choices[0].finish_reason);

        chat:chatCompletionResponseMessage message = choices[0].message;
        ai:ChatAssistantMessage|error chatAssistantMessage = self.convertChatCompletionsResponseToAssistantMessage(message);
        if chatAssistantMessage is error {
            span.close(chatAssistantMessage);
            return error ai:LlmInvalidResponseError("Error while parsing the model response", chatAssistantMessage);
        }
        if chatAssistantMessage.toolCalls is ai:FunctionCall[] {
            span.close();
            return chatAssistantMessage;
        }

        span.addOutputMessages(chatAssistantMessage);
        span.addOutputType(observe:TEXT);
        span.close();
        return chatAssistantMessage;
    }

    // ===== Responses API path =====

    private isolated function chatViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        [responses:InputItem[], string?]|ai:Error responseInput = convertToResponsesInput(messages);
        if responseInput is ai:Error {
            ai:Error err = error("Error while transforming input for Responses API", responseInput);
            span.close(err);
            return err;
        }
        [responses:InputItem[], string?] [inputItems, instructions] = responseInput;

        responses:createResponse request = {
            model: self.deploymentId,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: false
        };
        if self.temperature is decimal {
            request.temperature = self.temperature;
        }
        if instructions is string {
            request.instructions = instructions;
        }
        if stop is string {
            log:printWarn("The 'stop' parameter is not supported by the Responses API and will be ignored.",
                model = self.deploymentId);
        }

        if tools.length() > 0 {
            responses:Tool[]|error functionTools = convertToResponsesTools(tools);
            if functionTools is error {
                ai:Error err = error("Error while adding tools into Responses API", functionTools);
                span.close(err);
                return err;
            }
            request.tools = functionTools;
            span.addTools(tools);
        }
        responses:ReasoningEffort? reasoning = self.reasoning;
        if reasoning != () {
            request.reasoning = {effort: reasoning};
        }

        responses:response|error response = self.postResponses(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Responses API", err);
            span.close(err);
            return err;
        }

        ai:Error? statusError = checkResponseStatus(response);
        if statusError is ai:Error {
            span.close(statusError);
            return statusError;
        }

        span.addResponseId(response.id);
        responses:ResponseUsage? usage = response.usage;
        if usage is responses:ResponseUsage {
            span.addInputTokenCount(usage.input_tokens);
            span.addOutputTokenCount(usage.output_tokens);
        }
        span.addFinishReason(response.status ?: "completed");

        ai:ChatAssistantMessage|ai:Error message = convertResponsesOutputToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // Dispatches the prepared Responses request to the configured surface. See `postResponsesRequest` for the
    // v1-GA-vs-legacy-preview routing rules.
    private isolated function postResponses(responses:createResponse request) returns responses:response|error =>
        postResponsesRequest(self.responsesClient, self.legacyResponsesClient, self.useV1Responses,
                self.apiKey, self.apiVersion, request);

    // ===== Chat Completions helper methods =====

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages)
            returns chat:chatCompletionRequestMessage[]|ai:Error {
        chat:chatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push(check self.mapToAzureChatMessage(messages));
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage|ai:ChatSystemMessage {
                chatCompletionRequestMessages.push(check self.mapToAzureChatMessage(message));
            } else if message is ai:ChatAssistantMessage {
                chat:chatCompletionRequestAssistantMessage assistantMessage = {role: ai:ASSISTANT};
                ai:FunctionCall[]? toolCalls = message.toolCalls;
                if toolCalls is ai:FunctionCall[] && toolCalls.length() > 0 {
                    assistantMessage.tool_calls = from ai:FunctionCall tc in toolCalls
                        select {
                            id: tc.id ?: string `call_${tc.name}`,
                            'type: "function",
                            'function: {
                                name: tc.name,
                                arguments: (tc.arguments ?: {}).toJsonString()
                            }
                        };
                }
                string? content = message?.content;
                if content is string {
                    assistantMessage.content = content;
                }
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatFunctionMessage {
                chat:chatCompletionRequestToolMessage toolMessage = {
                    role: "tool",
                    content: message?.content ?: "",
                    tool_call_id: message.id ?: string `call_${message.name}`
                };
                chatCompletionRequestMessages.push(toolMessage);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function convertChatCompletionsResponseToAssistantMessage(
            chat:chatCompletionResponseMessage message) returns ai:ChatAssistantMessage|error {
        ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
        string? responseContent = message.content;
        chatAssistantMessage.content = responseContent;

        chat:chatCompletionMessageToolCall[]? toolCalls = message.tool_calls;
        if toolCalls is chat:chatCompletionMessageToolCall[] && toolCalls.length() > 0 {
            ai:FunctionCall[] functionCalls = [];
            foreach chat:chatCompletionMessageToolCall tc in toolCalls {
                json arguments = check tc.'function.arguments.fromJsonString();
                functionCalls.push({
                    id: tc.id,
                    name: tc.'function.name,
                    arguments: check arguments.cloneWithType()
                });
            }
            if functionCalls.length() > 0 {
                chatAssistantMessage.toolCalls = functionCalls;
            }
            return chatAssistantMessage;
        }

        // Fall back to the deprecated `function_call` field for backward compatibility.
        chat:chatCompletionFunctionCall? functionCall = message.function_call;
        if functionCall is chat:chatCompletionFunctionCall {
            json arguments = check functionCall.arguments.fromJsonString();
            chatAssistantMessage.toolCalls = [
                {
                    name: functionCall.name,
                    arguments: check arguments.cloneWithType()
                }
            ];
        }
        return chatAssistantMessage;
    }

    private isolated function mapToAzureChatMessage(ai:ChatUserMessage|ai:ChatSystemMessage message)
            returns chat:chatCompletionRequestUserMessage|chat:chatCompletionRequestSystemMessage|ai:Error {
        if message is ai:ChatSystemMessage {
            return {
                role: ai:SYSTEM,
                content: check getChatMessageStringContent(message.content),
                name: message.name
            };
        }
        return {
            role: ai:USER,
            content: check getChatMessageStringContent(message.content),
            name: message.name
        };
    }
}

# Posts a prepared Responses request to the configured Azure OpenAI Responses surface.
#
# - **v1 GA** (`useV1Responses` is `true`, i.e. the `serviceUrl` ends with `/v1`): the generated `responses:Client`
#   posts `/responses`, resolving to `POST {serviceUrl}/responses` with no `api-version`.
# - **Legacy preview** (otherwise): the raw HTTP client posts
#   `POST {serviceUrl}/openai/responses?api-version=${apiVersion}` with the `api-key` header. The request body is
#   serialized exactly as the generated connector serializes it (`createResponse` carries no rename annotations),
#   and the response is bound to `responses:response` with lax data binding, matching the v1 path.
#
# + responsesClient - The generated Responses connector used for the v1 GA surface (`()` on the legacy path)
# + legacyResponsesClient - The raw HTTP client used for the legacy preview route (`()` on the v1 path)
# + useV1Responses - `true` to target the v1 GA surface; `false` for the legacy preview route
# + apiKey - The Azure OpenAI API key, sent as the `api-key` header on the legacy route
# + apiVersion - The `api-version` query parameter value used on the legacy route
# + request - The prepared Responses request payload
# + return - The Responses API response, or an `error` on failure
isolated function postResponsesRequest(responses:Client? responsesClient, http:Client? legacyResponsesClient,
        boolean useV1Responses, string apiKey, string apiVersion, responses:createResponse request)
        returns responses:response|error {
    if useV1Responses {
        if responsesClient is () {
            return error("Responses v1 client is not initialized");
        }
        return responsesClient->/responses.post(request);
    }

    if legacyResponsesClient is () {
        return error("Legacy Responses client is not initialized");
    }
    map<string|string[]> headers = {"api-key": apiKey};
    return legacyResponsesClient->post(
            string `/responses?api-version=${apiVersion}`, request.toJson(), headers);
}

# Validates the status of an Azure OpenAI Responses API response and returns an error for any non-completed state.
#
# + response - The Responses API response
# + return - An `ai:Error` if the response did not complete successfully; otherwise `()`
isolated function checkResponseStatus(responses:response response) returns ai:Error? {
    string? status = response.status;
    if status == "failed" {
        string errorMsg = "Response generation failed";
        responses:ResponseError? responseError = response.'error;
        if responseError is responses:ResponseError {
            errorMsg = responseError.message;
        }
        return error ai:LlmConnectionError(errorMsg);
    }
    if status == "incomplete" {
        string errorMsg = "Response generation incomplete";
        responses:response_incomplete_details? details = response.incomplete_details;
        if details is responses:response_incomplete_details {
            errorMsg = string `Response incomplete: ${details.toString()}`;
        }
        return error ai:LlmInvalidResponseError(errorMsg);
    }
    if status == "in_progress" {
        return error ai:LlmConnectionError(
            "Response is still in_progress; use background mode with polling to handle async responses");
    }
    return;
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        json[] result = [];
        foreach ai:ChatMessage msg in messages {
            if msg is ai:ChatUserMessage|ai:ChatSystemMessage {
                result.push(check convertMessageToJson(msg));
            } else {
                result.push(msg);
            }
        }
        return result;
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {
        return {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
    }
    return messages;
}

isolated function convertFunctionsToCompletionTools(ai:ChatCompletionFunctions[] functions)
        returns chat:chatCompletionTool[] {
    return from ai:ChatCompletionFunctions fn in functions
        select {
            'type: "function",
            'function: {
                name: fn.name,
                description: fn.description,
                parameters: fn.parameters ?: {}
            }
        };
}
