// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/jballerina.java;
import ballerina/log;
import ballerinax/azure.openai.chat as chat;
import ballerinax/azure.openai.responses as responses;

const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# OpenAiProvider is a client class that provides an interface for interacting with Azure-hosted OpenAI language models.
# Supports both the Chat Completions API and the Responses API, selected via the `apiType` parameter.
public isolated client class OpenAiModelProvider {
    *ai:ModelProvider;
    private final chat:Client? llmClient;
    private final responses:Client? responsesClient;
    private final string deploymentId;
    private final chat:AzureAIFoundryModelsApiVersion? apiVersion;
    private final ApiType apiType;
    private final decimal? temperature;
    private final int maxTokens;
    private final (responses:OpenAI\.Reasoning & readonly)? reasoning;

    # Initializes the Azure OpenAI model with the given connection configuration and model configuration.
    #
    # + serviceUrl - The base URL of Azure OpenAI API endpoint
    # + apiKey - The Azure OpenAI API key
    # + deploymentId - The deployment identifier for the specific model deployment in Azure
    # + apiVersion - The Azure OpenAI API version (e.g., "2023-07-01-preview")
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + apiType - The API type to use (CHAT_COMPLETIONS or RESPONSES)
    # + reasoningEffort - Reasoning effort level for reasoning models
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "Service URL"} string serviceUrl,
            @display {label: "API Key"} string apiKey,
            @display {label: "Deployment ID"} string deploymentId,
            @display {label: "API Version"} chat:AzureAIFoundryModelsApiVersion? apiVersion = (),
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = DEFAULT_TEMPERATURE,
            @display {label: "API Type"} ApiType apiType = RESPONSES,
            @display {label: "Reasoning Effort"} responses:OpenAI\.Reasoning? reasoningEffort = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {

        self.deploymentId = deploymentId;
        self.apiVersion = apiVersion;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.apiType = apiType;
        self.reasoning = reasoningEffort.cloneReadOnly();

        chat:ConnectionConfig azureAiConfig = {
            auth: {api\-key: apiKey, authorization: ""},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig.poolConfig,
            cache: connectionConfig.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig.circuitBreaker,
            retryConfig: connectionConfig.retryConfig,
            responseLimits: connectionConfig.responseLimits ?: {},
            secureSocket: connectionConfig.secureSocket,
            proxy: connectionConfig.proxy,
            validation: connectionConfig.validation
        };

        if apiType == CHAT_COMPLETIONS {
            chat:Client|error llmClient = new (azureAiConfig, serviceUrl);
            if llmClient is error {
                return error ai:Error("Failed to initialize AzureOpenAiProvider", llmClient);
            }
            self.llmClient = llmClient;
            self.responsesClient = ();
        } else {
            responses:Client|error responsesApiClient = new (azureAiConfig, serviceUrl);
            if responsesApiClient is error {
                return error ai:Error("Failed to initialize chat:Client for Responses API", responsesApiClient);
            }
            self.responsesClient = responsesApiClient;
            self.llmClient = ();
        }
    }

    # Sends a chat request to the OpenAI model with the given messages and tools.
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages,
            (ai:ChatCompletionFunctions|ai:InbuiltModelTool)[] tools,
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {

        if self.apiType == RESPONSES {
            return self.chatViaResponses(messages, tools, stop);
        }

        string[] unsupportedTools = [];
        ai:ChatCompletionFunctions[] functionTools = [];
        foreach var tool in tools {
            if tool is ai:InbuiltModelTool {
                unsupportedTools.push(tool.name);
            } else {
                functionTools.push(tool);
            }
        }
        if unsupportedTools.length() > 0 {
            return error ai:Error(string `Inbuilt tools [${string:'join(", ", ...unsupportedTools)}] are not supported `
                + "for the Chat Completions API. Use apiType = RESPONSES instead.");
        }

        return self.chatViaChatCompletions(messages, functionTools, stop);
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.azure.Generator"
    } external;

    // ===== Chat Completions API path =====

    private isolated function chatViaChatCompletions(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        log:printInfo("Chat Completion API has been called");
        chat:Client llmClient = <chat:Client>self.llmClient;
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        span.addOutputType(observe:TEXT);
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error jsonMsg = check convertMessageToJson(messages);
        if jsonMsg is ai:Error {
            ai:Error err = error("Error while transforming input", jsonMsg);
            span.close(err);
            return err;
        }
        span.addInputMessages(jsonMsg);

        chat:chat_completions_body request = {
            stop,
            messages: check self.prepareCompletionRequestMessages(messages, tools),
            model: self.deploymentId,
            temperature: self.temperature,
            max_completion_tokens: self.maxTokens
        };
        if tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }

        chat:inline_response_200|error response =
            llmClient->/chat/completions.post(request, queries = {api\-version: self.apiVersion});
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }
        log:printInfo("Raw Chat Completions response received", response = response.toJsonString());

        record {|
            "stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason;
            int index;
            chat:OpenAI\.ChatCompletionResponseMessage message;
            anydata logprobs?;
            anydata...;
        |}[] choices = let var r = response in r is record {|chat:OpenAI\.CreateChatCompletionResponseChoices[] choices; anydata...;|} ? r.choices : [];

        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        string|int? responseId = response is record {|string id; anydata...;|} ? response.id : ();
        if responseId is string {
            span.addResponseId(responseId);
        }
        anydata usage = response is record {|anydata usage; anydata...;|} ? response.usage : ();
        if usage is record {|int prompt_tokens; int completion_tokens; anydata...;|} {
            span.addInputTokenCount(usage.prompt_tokens);
            span.addOutputTokenCount(usage.completion_tokens);
        }
        string? finishReason = choices[0].finish_reason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        chat:OpenAI\.ChatCompletionResponseMessage? message = choices[0].message;
        ai:ChatAssistantMessage|error chatAssistantMessage = self.convertChatCompletionsResponseToAssistantMessage(message);
        if chatAssistantMessage is error {
            span.close(chatAssistantMessage);
            return error ai:LlmInvalidResponseError("Error while parsing the model response", chatAssistantMessage);
        }
        if chatAssistantMessage.toolCalls is ai:FunctionCall[] {
            return chatAssistantMessage;
        }
        
        span.addOutputMessages(chatAssistantMessage);
        span.addOutputType(observe:TEXT);
        span.close();
        return chatAssistantMessage;
    }

    // ===== Responses API path =====

    private isolated function chatViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            (ai:ChatCompletionFunctions|ai:InbuiltModelTool)[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        log:printInfo("Responses API has been called");
        responses:Client responsesClient = <responses:Client>self.responsesClient;
        observe:ChatSpan span = observe:createChatSpan(self.deploymentId);
        span.addProvider("azure.ai.openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        // Separate function tools and inbuilt tools
        ai:ChatCompletionFunctions[] functionToolDefs = [];
        ai:InbuiltModelTool[] inbuiltToolDefs = [];
        foreach var tool in tools {
            if tool is ai:ChatCompletionFunctions {
                functionToolDefs.push(tool);
            } else {
                inbuiltToolDefs.push(tool);
            }
        }

        // Convert messages to Responses API input format
        [responses:OpenAI\.InputParam, string?] [inputItems, instructions] = check convertToResponsesInput(messages, functionToolDefs);

        responses:OpenAI\.CreateResponse request = {
            model: self.deploymentId,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: true
        };
        if self.temperature is decimal {
            request.temperature = self.temperature;
        }

        if instructions is string {
            request.instructions = instructions;
        }
        if stop is string {
            log:printWarn("The 'stop' parameter is not supported by the Responses API and will be ignored.",
                model = self.deploymentId);
        }
        responses:OpenAI\.Tool[] allTools = [];
        if functionToolDefs.length() > 0 {
            responses:OpenAI\.Tool[] functionTools = convertToResponsesTools(functionToolDefs);
            foreach responses:OpenAI\.Tool ft in functionTools {
                allTools.push(ft);
            }
        }
        if inbuiltToolDefs.length() > 0 {
            responses:OpenAI\.Tool[] convertedInbuiltTools = check convertInbuiltToolsToResponsesFormat(inbuiltToolDefs);
            foreach responses:OpenAI\.Tool t in convertedInbuiltTools {
                allTools.push(t);
            }
        }
        if tools.length() > 0 {
            json[] toolsArr = [];
            foreach ai:ChatCompletionFunctions|ai:InbuiltModelTool tool in tools {
                if tool is ai:ChatCompletionFunctions {
                    toolsArr.push(tool);
                } else {
                    toolsArr.push(tool.toJson());
                }
            }
            span.addTools(toolsArr);
        }
        if allTools.length() > 0 {
            request.tools = allTools;
        }
        if self.reasoning is responses:OpenAI\.Reasoning {
            request.reasoning = self.reasoning;
        }

        // POST to /responses
        // anydata|error response2 = responsesClient->/responses.post(request,
        //     queries = {api\-version: self.apiVersion});
        // if response2 is error {
        //     ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response2);
        //     span.close(err);
        //     return err;
        // }
        // log:printInfo("Raw Responses API response received", response = response2.toJson());


        // chat:inline_response_200_5 response = <chat:inline_response_200_5>response2;

        responses:inline_response_200_5|error response = responsesClient->/responses.post(request,
            queries = {api\-version: self.apiVersion});
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }
        log:printInfo("Raw Responses API response received", response = response.toJson());


        // Handle non-completed statuses
        string? status = response?.status;
        if status == "failed" {
            string errorMsg = "Response generation failed";
            anydata responseError = response.'error;
            if responseError != () {
                errorMsg = responseError.toString();
            }
            ai:Error err = error ai:LlmConnectionError(errorMsg);
            span.close(err);
            return err;
        }
        if status == "incomplete" {
            string errorMsg = "Response generation incomplete";
            anydata details = response.incomplete_details;
            if details != () {
                errorMsg = string `Response incomplete: ${details.toString()}`;
            }
            ai:Error err = error ai:LlmInvalidResponseError(errorMsg);
            span.close(err);
            return err;
        }
        if status == "cancelled" {
            ai:Error err = error ai:LlmConnectionError("Response generation was cancelled");
            span.close(err);
            return err;
        }
        if status == "in_progress" || status == "queued" {
            ai:Error err = error ai:LlmConnectionError(
                string `Response is still ${status}; use background mode with polling to handle async responses`);
            span.close(err);
            return err;
        }

        // Record observability
        span.addResponseId(response.id);
        responses:OpenAI\.ResponseUsage? usage = response.usage;
        if usage is responses:OpenAI\.ResponseUsage {
            span.addInputTokenCount(usage.input_tokens);
            span.addOutputTokenCount(usage.output_tokens);
        }
        span.addFinishReason(status ?: "completed");

        // Parse response output into ai:ChatAssistantMessage
        ai:ChatAssistantMessage|ai:Error message = convertResponsesOutputToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // ===== Chat Completions helper methods =====

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns chat:OpenAI\.ChatCompletionRequestMessage[]|ai:Error {
        chat:OpenAI\.ChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push(check self.mapToAzureChatMessage(messages));
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage|ai:ChatSystemMessage {
                chatCompletionRequestMessages.push(check self.mapToAzureChatMessage(message));
            } else if message is ai:ChatAssistantMessage {
                chat:OpenAI\.ChatCompletionRequestMessage assistantMessage = {role: ai:ASSISTANT};
                ai:FunctionCall[]? toolCalls = message.toolCalls;
                if toolCalls is ai:FunctionCall[] && toolCalls.length() > 0 {
                    assistantMessage["tool_calls"] = from ai:FunctionCall tc in toolCalls
                        select {
                            id: tc.id ?: string `call_${tc.name}`,
                            'type: "function",
                            'function: {
                                name: tc.name,
                                arguments: (tc.arguments ?: {}).toJsonString()
                            }
                        };
                }
                if message?.content is string {
                    assistantMessage["content"] = message?.content;
                }
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatFunctionMessage {
                chatCompletionRequestMessages.push(message);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function convertChatCompletionsResponseToAssistantMessage(
            chat:OpenAI\.ChatCompletionResponseMessage? message) returns ai:ChatAssistantMessage|error {
        ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
        anydata responseContent = message?.content;
        chatAssistantMessage.content = responseContent is string ? responseContent : ();

        // Use modern tool_calls format
        chat:OpenAI\.ChatCompletionMessageToolCallsItem? toolCalls = message?.tool_calls;
        if toolCalls is (chat:OpenAI\.ChatCompletionMessageToolCall|chat:OpenAI\.ChatCompletionMessageCustomToolCall)[] && toolCalls.length() > 0 {
            ai:FunctionCall[] functionCalls = [];
            foreach var tc in toolCalls {
                if tc is chat:OpenAI\.ChatCompletionMessageToolCall {
                    json arguments = check tc.'function.arguments.fromJsonString();
                    functionCalls.push({
                        id: tc.id,
                        name: tc.'function.name,
                        arguments: check arguments.cloneWithType()
                    });
                }
            }
            if functionCalls.length() > 0 {
                chatAssistantMessage.toolCalls = functionCalls;
            }
            return chatAssistantMessage;
        }

        // Fall back to deprecated function_call for backward compatibility
        chat:OpenAI\.ChatCompletionResponseMessageFunctionCall? functionCall = message?.function_call;
        if functionCall is chat:OpenAI\.ChatCompletionResponseMessageFunctionCall {
            json arguments = check functionCall.arguments.fromJsonString();
            chatAssistantMessage.toolCalls = [
                {
                    name: functionCall.name,
                    arguments: check arguments.cloneWithType()
                }
            ];
        }
        return chatAssistantMessage;
    }

    private isolated function mapToAzureChatMessage(ai:ChatUserMessage|ai:ChatSystemMessage message)
    returns AzureChatUserMessage|AzureChatSystemMessage|ai:Error {
        if message is ai:ChatSystemMessage {
            return {
                role: ai:SYSTEM,
                content: check getChatMessageStringContent(message.content),
                name: message.name
            };
        }
        return {
            role: ai:USER,
            content: check getChatMessageStringContent(message.content),
            name: message.name
        };
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        json[] result = [];
        foreach ai:ChatMessage msg in messages {
            if msg is ai:ChatUserMessage|ai:ChatSystemMessage {
                result.push(check convertMessageToJson(msg));
            } else {
                result.push(msg);
            }
        }
        return result;
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {
        return {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
    }
    return messages;
}

isolated function convertFunctionsToCompletionTools(ai:ChatCompletionFunctions[] functions) returns chat:OpenAI\.ChatCompletionTool[] {
    return from ai:ChatCompletionFunctions fn in functions
        select <chat:OpenAI\.ChatCompletionTool>{
            'type: "function",
            'function: {
                name: fn.name,
                description: fn.description,
                parameters: fn.parameters ?: {}
            }
        };
}
